template = "https://github.com/giellalt/template-lang-und"
rev_id = 289
template_sha = "599009dae90448ef6fe32b71f7a6880293f3d546"

[replacements]
__GLOTTOLOG_ID__ = "kalo1256"
__REPO__ = "lang-rmf"
__UND2C__ = "rmf"
__UNDEFINED__ = "Kalo Finnish Romani"
__UND__ = "rmf"
