template = "https://github.com/giellalt/template-lang-und"
rev_id = 328
template_sha = "a66ce6606ea33e46cd3439c88cafa44d4dcdde92"

[replacements]
__GLOTTOLOG_ID__ = "kalo1256"
__REPO__ = "lang-rmf"
__UND2C__ = "rmf"
__UNDEFINED__ = "Kalo Finnish Romani"
__UND__ = "rmf"
