template = "https://github.com/giellalt/template-lang-und"
rev_id = 298
template_sha = "4822abccfb9b3ce82bf2876217cde02b5f647d14"

[replacements]
__GLOTTOLOG_ID__ = "kalo1256"
__REPO__ = "lang-rmf"
__UND2C__ = "rmf"
__UNDEFINED__ = "Kalo Finnish Romani"
__UND__ = "rmf"
