[package]
name = "rmf"
human_name = "Kalo Finnish Romani"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.rmf]
filename = "rmf-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-rmf"
platform = "windows"
uuid = "23C71AE7-DDB6-41B6-83FB-6E27D2C50297"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.rmf"
package = "speller-rmf"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-rmf-mso"
platform = "windows"
uuid = "14EA3748-8B4B-486F-A3C9-CF0580321E06"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-rmf"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
